version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - dogsled
    - errchkjson
    - errname
    - errorlint
    - goheader
    - goprintffuncname
    - gosec
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - protogetter
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - wastedassign
    - zerologlint
  settings:
    govet:
      enable:
        - nilness
        - printf
        - unusedresult
    nakedret:
      max-func-lines: 30
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
